//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaGad.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        public film()
        {
            this.session = new HashSet<session>();
        }
    
        public int film_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<session> session { get; set; }
    }
}
